### ISSUE TITLE
Widget setting PHP notices before first save

### ISSUE THREAD

**Issue by SeanChDavis** [topher1kenobe/heropress-recent-essay-widget#1]
- Notice: Undefined index: heropress-show-banner in /Applications/MAMP/htdocs/localhost/edd/wp-content/plugins/heropress-recent-essay-widget-master/heropress-recent-essays-widget.php on line 274
- Notice: Undefined index: heropress-show-title in /Applications/MAMP/htdocs/localhost/edd/wp-content/plugins/heropress-recent-essay-widget-master/heropress-recent-essays-widget.php on line 278
- Notice: Undefined index: heropress-show-author in /Applications/MAMP/htdocs/localhost/edd/wp-content/plugins/heropress-recent-essay-widget-master/heropress-recent-essays-widget.php on line 282
- Notice: Undefined index: heropress-show-pubdate in /Applications/MAMP/htdocs/localhost/edd/wp-content/plugins/heropress-recent-essay-widget-master/heropress-recent-essays-widget.php on line 286

**Comment by topher1kenobe** [comment]
and also taken care of.
