### ISSUE TITLE
Missing translation functions

### ISSUE THREAD

**Issue by SeanChDavis** [topher1kenobe/heropress-recent-essay-widget#3]
`Show:` https://github.com/topher1kenobe/heropress-recent-essay-widget/blob/master/heropress-recent-essays-widget.php#L271

**Comment by SeanChDavis** [comment]
Also the labels for all four settings, starting here: https://github.com/topher1kenobe/heropress-recent-essay-widget/blob/master/heropress-recent-essays-widget.php#L275

**Comment by topher1kenobe** [comment]
Thanks Sean, this is taken care of.
